server:
  port: 8081
  version: local
application:
  unhealthy_seconds: 10
  ipv4: 127.0.0.1
management:
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          up: 200
          unknown: 500
          down: 503
  endpoints:
    web:
      base-path: "/private/actuator"
      exposure:
        include: health